
## 📌 O que é uma CTE?

Uma CTE (Common Table Expression) é uma construção no SQL que permite criar uma tabela temporária nomeada dentro de uma consulta. Isso melhora a legibilidade e organização do código, facilitando a reutilização e a manutenção das queries.

As CTEs são declaradas com a palavra-chave **WITH** , seguida pelo nome da expressão, nomes opcionais das colunas e a consulta SQL que define seus dados.

### 📌 Sintaxe Básica de uma CTE:

``` sql
WITH nome_da_CTE (coluna1, coluna2, ...) AS (
    -- Consulta que define a CTE
    SELECT coluna1, coluna2
    FROM tabela_origem
    WHERE condição
)
-- Consulta principal que usa a CTE
SELECT *
FROM nome_da_CTE;
```

#### \*\* 🎯 Benefícios do Uso de CTEs:\*\*
<br>
✅ **Melhor organização do código** – Permite dividir consultas complexas em partes menores e reutilizáveis.
✅ **Reutilização de código** – Pode ser referenciada várias vezes dentro da mesma consulta, evitando duplicação.
✅ **Facilidade de leitura e manutenção** – Evita subqueries aninhadas difíceis de interpretar.
✅ **Melhoria de performance** – Em alguns casos, pode otimizar a execução evitando junções repetitivas.
✅ **Facilidade para consultas recursivas** – Muito útil para estruturar hierarquias, como organogramas de empresas ou árvores genealógicas.
<br>
##### 🔎 Exemplo 1: Uso básico de uma CTE

Vamos supor que temos uma tabela vendas e queremos calcular as vendas médias por cliente:

``` sql
WITH vendas_cliente AS (
    SELECT cliente_id, SUM(valor) AS total_vendas
    FROM vendas
    GROUP BY cliente_id
)
SELECT cliente_id, total_vendas
FROM vendas_cliente
WHERE total_vendas > 1000;
```

##### 🔎 Exemplo 2: CTE para Filtragem e Organização de Dados
<br>
Vamos supor que temos uma tabela de pedidos (orders) e queremos calcular o valor médio dos pedidos por cliente e depois filtrar apenas aqueles com ticket médio acima de R$ 500,00.
<br>
``` sql
WITH media_pedidos AS (
    SELECT cliente_id, AVG(valor_total) AS ticket_medio
    FROM orders
    GROUP BY cliente_id
)
SELECT cliente_id, ticket_medio
FROM media_pedidos
WHERE ticket_medio > 500;
```

O que está acontecendo aqui?
1️⃣ A CTE media\_pedidos calcula o ticket médio de cada cliente.
2️⃣ Depois, na consulta principal, filtramos apenas clientes cujo ticket médio seja maior que R$ 500,00.

🎯 Benefícios dessa abordagem:
✅ Deixamos a query mais organizada e fácil de entender.
✅ Evitamos a repetição da agregação (AVG(valor\_total)) em múltiplas partes da consulta.
✅ Podemos reutilizar a CTE para outras análises dentro da mesma query.

🚀 Conclusão
As CTEs são ferramentas poderosas no SQL, trazendo organização, eficiência e reutilização para consultas complexas. Elas são especialmente úteis para cálculos agregados, hierarquias e substituição de subqueries complicadas.